[package]
name = "loxi"
version = "0.1.0"
edition = "2021"

[features]
# default = ["unicode"]
unicode = []

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
fnv = "1.0.7"
indoc = "2.0.5"
lasso = "0.7.3"
thiserror = "1.0.63"
unicode-width = "0.1.13"
